command_timeout = 500
scan_timeout = 10

[character]
success_symbol = "[âœ](bold green)"
error_symbol = " [Î»](bold red)"

[aws]
disabled=true

[cmd_duration]
format = ""

[time]
disabled = true
time_format = "%T"
format = "[$time]($style)"
utc_time_offset = "+1"

[git_branch]
symbol = "ğŸŒ± "

[git_commit]
commit_hash_length = 5
tag_symbol = "ğŸ”– "

[git_status]
conflicted = "ğŸ³"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[python]
pyenv_version_name=false

[container]
format = "[$symbol \\[$name\\]]($style) "
